### ISSUE TITLE
pagination_tag

### ISSUE THREAD

**Issue by Mbusokhoza** [a1tus/django-admin-cursor-paginator#1]
When an admin model specifies a custom list change_list_template the following error is thrown 

```Traceback (most recent call last):
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/.virtualenvs/ls-core/lib/python3.8/site-packages/django/contrib/admin/templatetags/admin_list.py", line 62, in pagination
    if paginator.num_pages <= 10:

Exception Type: AttributeError at /admin/.../..../
Exception Value: 'AdminCursorPaginator' object has no attribute 'num_pages'```

**Comment by a1tus** [comment]
Cursor pagination is shown via custom tag. All you need is to override pagination block like that:

https://github.com/a1tus/django-admin-cursor-paginator/blob/main/admin_cursor_paginator/templates/admin_cursor_paginator/change_list.html

**Comment by Mbusokhoza** [comment]
@a1tus Thanks, I eventually figured it out :) perhaps this something you should add to your documentation. Thanks for the speedy response.
